name: assignment3

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log job start
        run: |
          echo $(date -Iminutes) > log.txt
          echo Bar Nir and Niv Machlis >> log.txt
      - name: Build Docker image
        run: docker build -t dish_meal_services .
      - name: On success
        if: ${{ success() }}
        run: echo image successfully built >> log.txt
      - name: On failure
        if: ${{ failure() }}
        run: echo image not able to be built >> log.txt
      - name: Save Docker image
        run: docker save dish_meal_services | gzip > dish_meal_services.tar.gz
      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v2
        with:
          name: dish_meal_services
          path: dish_meal_services.tar.gz
      - name: Upload job start log
        uses: actions/upload-artifact@v2
        with:
          name: log.txt
          path: log.txt

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker image from artifact
        uses: actions/download-artifact@v2
        with:
          name: dish_meal_services
      - name: Load Docker image
        run: docker load < dish_meal_services.tar.gz
      - name: Run Docker image
        env:
          NINJA_API_KEY: ${{secrets.NINJA_API_KEY}}
        run: |
          docker run -e NINJA_API_KEY -p 8000:8000 -d dish_meal_services
          docker ps
      - name: On success
        if: ${{ success() }}
        run: echo Container up and running >> log.txt
      - name: On failure
        if: ${{ failure() }}
        run: echo Container failed to run >> log.txt
      - name: Wait for docker container
        run: sleep 5
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run tests
        run: |
          sleep 5
          docker ps
          pytest tests/assn3_tests.py
      - name: On success
        if: ${{ success() }}
        run: echo tests succeeded >> log.txt
      - name: On failure
        if: ${{ failure() }}
        run: echo tests failed >> log.txt
      - uses: actions/checkout@v2
      - name: Upload job start log
        uses: actions/upload-artifact@v2
        with:
          name: log.txt
          path: log.txt

  query:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log job start
        run: echo "Query job started at $(date)" > query-job-start.log
      - name: Download Docker image from artifact
        uses: actions/download-artifact@v2
        with:
          name: dish_meal_services
      - name: Load Docker image
        run: docker load < dish_meal_services.tar.gz
      - name: Run Docker image
        env:
          NINJA_API_KEY: ${{secrets.NINJA_API_KEY}}
        run: |
          docker run -e NINJA_API_KEY -p 8000:8000 -d dish_meal_services
          docker ps
      - name: Wait for docker container
        run: sleep 5
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run job
        run: |
          sleep 5
          docker ps
          python ./jobProcess.py
      - name: Upload response.txt
        uses: actions/upload-artifact@v2
        with:
          name: response.txt
          path: ./response.txt
